[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 524, in <module>
    trainer.benchmark_step()
  File "main_gpt2_with_health_checker.py", line 393, in benchmark_step
    loss = outputs[0] 
NameError: name 'outputs' is not defined
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 524, in <module>
    trainer.benchmark_step()
  File "main_gpt2_with_health_checker.py", line 393, in benchmark_step
    loss = outputs[0] 
NameError: name 'outputs' is not defined
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 524, in <module>
    trainer.benchmark_step()
  File "main_gpt2_with_health_checker.py", line 393, in benchmark_step
    loss = outputs[0] 
NameError: name 'outputs' is not defined
Traceback (most recent call last):
  File "main_gpt2_with_health_checker.py", line 524, in <module>
    trainer.benchmark_step()
  File "main_gpt2_with_health_checker.py", line 393, in benchmark_step
    loss = outputs[0] 
NameError: name 'outputs' is not defined
srun: error: gpu07: tasks 0,2: Exited with exit code 1
srun: error: gpu07: tasks 1,3: Exited with exit code 1
