[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
srun: error: gpu12: task 1: Exited with exit code 1
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
srun: error: gpu13: task 4: Exited with exit code 1
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
  0%|          | 0/300 [00:00<?, ?it/s]  0%|          | 0/300 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "test_fsdp_fairscale0.4.py", line 89, in <module>
    print(batch[0].shape())
TypeError: 'torch.Size' object is not callable
srun: error: gpu13: task 6: Exited with exit code 1
srun: error: gpu12: tasks 2-3: Exited with exit code 1
srun: error: gpu12: task 0: Exited with exit code 1
srun: error: gpu13: task 7: Exited with exit code 1
srun: error: gpu13: task 5: Exited with exit code 1
