[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Traceback (most recent call last):
  File "run.py", line 106, in <module>
    '--rank', str(args.rank), 
AttributeError: 'Namespace' object has no attribute 'rank'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 138, in <module>
    f.write(str(out[1]))
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 156, in <module>
    print(proc.pid)
AttributeError: 'NoneType' object has no attribute 'pid'
Traceback (most recent call last):
  File "run.py", line 106, in <module>
    '--rank', str(args.rank), 
AttributeError: 'Namespace' object has no attribute 'rank'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 138, in <module>
    f.write(str(out[1]))
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 156, in <module>
    print(proc.pid)
AttributeError: 'NoneType' object has no attribute 'pid'
Traceback (most recent call last):
  File "run.py", line 106, in <module>
    '--rank', str(args.rank), 
AttributeError: 'Namespace' object has no attribute 'rank'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 138, in <module>
    f.write(str(out[1]))
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 156, in <module>
    print(proc.pid)
AttributeError: 'NoneType' object has no attribute 'pid'
Traceback (most recent call last):
  File "run.py", line 106, in <module>
    '--rank', str(args.rank), 
AttributeError: 'Namespace' object has no attribute 'rank'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 138, in <module>
    f.write(str(out[1]))
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 156, in <module>
    print(proc.pid)
AttributeError: 'NoneType' object has no attribute 'pid'
srun: error: gpu20: tasks 0-1: Exited with exit code 1
srun: error: gpu21: tasks 2-3: Exited with exit code 1
