[00;33m 	'cuda/11.3' does not supports the {CUDA_MPI}. [0m
[00;34m 	{CUDA_MPI} is only supported in cuda 11.4 version. [0m
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
Traceback (most recent call last):
  File "main_gpt2_allreduce_backupr.py", line 522, in <module>
    trainer.benchmark_step()
  File "main_gpt2_allreduce_backupr.py", line 394, in benchmark_step
    while not handle.is_completed():
AttributeError: 'NoneType' object has no attribute 'is_completed'
srun: error: gpu20: tasks 0-1: Exited with exit code 1
srun: error: gpu21: tasks 4-6: Exited with exit code 1
srun: error: gpu20: tasks 2-3: Exited with exit code 1
srun: error: gpu21: task 7: Exited with exit code 1
